platform :ios, '10.0'
use_frameworks!
install! 'cocoapods', :generate_multiple_pod_projects => true

target 'EmptyPage_Example' do
  pod 'EmptyPage', :path => '../EmptyPage.podspec'
  pod 'SnapKit', '5.0.0'
  pod 'Hue'
  pod 'SVProgressHUD'
end
